# permissions for end users to edit todoapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: todoapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: quickbytes-demo
    app.kubernetes.io/part-of: quickbytes-demo
    app.kubernetes.io/managed-by: kustomize
  name: todoapp-editor-role
rules:
- apiGroups:
  - saas.thoughtworks.com
  resources:
  - todoapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.thoughtworks.com
  resources:
  - todoapps/status
  verbs:
  - get
